### ISSUE TITLE
请问console里的onebotchannel到底填什么

### ISSUE THREAD

**Issue by yds1301703077** [koishijs/koishi-plugin-dcqq-relay#17]
discordlogchannel也不知道填什么
[W] diagnostic plugin dcqq-relay is missing required service database
纯纯的电脑小白

**Comment by XxLittleCxX** [comment]
> onebotchannel到底填什么

QQ 平台的群号

> discordlogchannel也不知道填什么

Discord 的频道 ID，非必填，用来记录撤回的消息

> [W] diagnostic plugin dcqq-relay is missing required service database

参考 [koishi 文档](https://koishi.js.org/manual/console/market.html)，安装数据库后启用插件

**Comment by yds1301703077** [comment]
emmmm 数据库换了两个都显示 app duplicate plugin detected: undefined
到底是哪里出错了呢
真的非常感谢你有耐心如此迅速的回复🥺 本没有抱有会被回复的期待 谢谢你
![QQ截图20220826095851](https://user-images.githubusercontent.com/55316491/186852993-49fd4bf2-8a03-4d19-b331-9d229096fbd6.jpg)
![QQ截图20220826095841](https://user-images.githubusercontent.com/55316491/186852995-6086ec62-4399-47c3-a6a4-87212ab94b45.jpg)

**Comment by yds1301703077** [comment]
谢谢我已经不搞了所以不用回复了
