### ISSUE TITLE
【建议】能否在dc->qq转发时，添加上dc的头像

### ISSUE THREAD

**Issue by adquantum** [koishijs/koishi-plugin-dcqq-relay#20]
感谢大佬的插件
建议在在dc->qq转发时，添加上dc的头像，或者增加这个配置选项
在qq上看纯文字体验挺不好

**Comment by DoroWolf** [comment]
QQ不像discord一样可以分别设置头像，QQ只设定头像就够麻烦了，还要高强度更换...

**Comment by adquantum** [comment]
> QQ不像discord一样可以分别设置头像，QQ只设定头像就够麻烦了，还要高强度更换...

如果只是简单地像转发id一样，带上头像，把头像也作为转发内容输出呢，虽然效果不尽完美，但是在qq侧看起来更直观一些？

**Comment by OasisAkari** [comment]
效果会非常差

要么一条消息头像撑起一半以上的消息框，要么头像特别糊没办法看

**Comment by adquantum** [comment]
> 效果会非常差
> 
> 要么一条消息头像撑起一半以上的消息框，要么头像特别糊没办法看

那能不能对qq侧发送的头像限定大小?这是另一个插件的效果，观感还行？但是他们的那个我用不来
![image](https://user-images.githubusercontent.com/85437732/230262203-1909288b-707b-403e-b169-5fd68a5a3920.png)

**Comment by Dianliang233** [comment]
qq并没有限定图片大小的功能，只是输出的图片小罢了。以及在移动端大小图片都一视同仁一样大的。

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by OasisAkari** [comment]
电脑上看上去可能还好
![image](https://user-images.githubusercontent.com/31803608/230266005-2f516139-4d66-403d-93f7-e21485708470.png)
但是得益于tx的迷之图片缩放算法，手机上大概率会是这样
![`}0_(UW@W2I_S4`7K ZIXJC](https://user-images.githubusercontent.com/31803608/230266196-597e0111-93f6-4e69-ab2d-21c294782ff9.jpg)

**Comment by adquantum** [comment]
好叭，我知道了，看来确实不太可行

**Comment by adquantum** [comment]
discord 的cdn，可以自带?size 参数，我自己这样修改了，感觉效果良好？
        result.push(koishi_1.segment.image(`${session.author.avatar}?size=40`));
        result.push(`${username}: \n`);
