### ISSUE TITLE
qq发送到dc的动图不再会动

### ISSUE THREAD

**Issue by adquantum** [koishijs/koishi-plugin-dcqq-relay#21]
从0.6.0更新到0.7.0，动图在dc不会动了，转发给dc的地址例如
https://gchat.qpic.cn/gchatpic_new/1782213257/706198168-3027411880-C256E3CBFA26618B00B7122E8FE74F0F/0?term=255&is_origin=0

**Comment by XxLittleCxX** [comment]
也许是 discord 预览服务器的改动，不确定和插件版本有没有关系，请在 `adapter-discord` 配置项加入 `handleExternalAsset: download`（注意这会显著增加网络流量）

**Comment by adquantum** [comment]
了解啦，感谢
