### ISSUE TITLE
dc侧接受qq侧文件，文件命名不对，需要重命名才能打开

### ISSUE THREAD

**Issue by adquantum** [koishijs/koishi-plugin-dcqq-relay#23]
例如qq发送视频，dc就会收到如下文件
[qqdownload.bin](https://cdn.discordapp.com/attachments/468295821788708876/1113341485086154825/qqdownload.bin)

**Comment by XxLittleCxX** [comment]
本地修了，还没推，再等几天（

**Comment by XxLittleCxX** [comment]
https://github.com/koishijs/koishi-plugin-dcqq-relay/commit/d0659e7d342efd79a5283b557ed55ec3af4bf484
